name = "optional"
description = "Optional values a la java.lang.Optional"
version = "0.2.0"

tags = ["optional", "functional"]
licenses = "LGPL-3.0-only"
website = "https://github.com/mosteo/optional/"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]

[[actions]]
type = "test"
command = ["alr", "build"]
directory = "examples"
